export enum ServerError {
    WRONG_USERNAME,
    WRONG_ID,
    EMPTY_ID,
    TOO_LONG_CHAT_MESSAGE,
    CLIENT_CONNECTION_ERROR,
    PLAYER_ALREADY_CONNECTED,
    ADMIN_KEY_ENV_NOT_EXIST,
    WRONG_ADMIN_KEY,
    PLAYER_LIMIT_REACHED
}
